name: Test Package
author: mralfiem591
version: 1.0.0
description: A test package to ensure PaxD works correctly.
license: MIT
tags:
- test
- example
- cli
- windows
install:
  files:
  - test.py
  - LICENSE
  dependencies:
    paxd:
    - com.mralfiem591.paxd-sdk
  firstrun: false
  updaterun: false
  supports_fastxd: true
  main_executable: test.py
  command_alias: paxd-test
  checksum:
    LICENSE: sha256:f5382f6ba1a0e00d6eeed6e1ce4430b552a3e694b61a529526c29ccaeacea11f
    test.py: sha256:33337c1ac14705b152d3818f274dcaf839f31ce5ff78633b5056f91e2ac1b889
