name: PaxD Compiler
author: mralfiem591
version: 1.0.0
description: The main command line tool for using the new YAML PaxD format.
license: MIT
tags:
- cli
- compiler
- paxd
install:
  files:
  - main.py
  dependencies:
    pip:
    - pyyaml
  firstrun: false
  updaterun: false
  supports_fastxd: true
  main_executable: main.py
  command_alias: paxd-compile
  checksums:
    main.py: sha256:a2c12d67443bbcf6da4c59f6b6ba21640772854dd2cf6b50683d1acb210c4fed
