name: PaxD
author: mralfiem591
version: 26.0.12
description: The main command line tool for using PaxD.
license: MIT
tags:
- cli
- package manager
- installer
- windows
- tool
- gateway
- http
- repository
install:
  files:
  - paxd.py
  - run_pkg.py
  - repository
  - LICENSE
  dependencies:
    pip:
    - requests
    - colorama
    - argparse
    - pyyaml
    - sentry-sdk
    - uv
    paxd:
    - com.mralfiem591.paxd-sdk
    - com.mralfiem591.paxd-imageview
  checksums:
    LICENSE: sha256:c856d6c33a97f74f274e7d7bee176b0515f34631d34642ec95a0156df614e207
    paxd.py: sha256:f124c81c84f82d8682402ad330eb57f94dd68edf133837d027418f28386342fd
    repository: sha256:e27899b5a8509be78d4e9ffb36fb87d2b9ac9610356bbf9478e05a52ed7b6784
    run_pkg.py: sha256:589eb81104b6a77bb68111fd70bb71b2c65ffe3d811d60a0d44557aa2b3cf791
    asset/logo.png: sha256:439524e5fbead18454271c1fb316465c5bb3189cf19a0596db757f5396988e61
  firstrun: true
  updaterun: true
  exclude_from_updates:
  - repository
  main_executable: paxd.py
  command_alias: paxd
  supports_fastxd: false
