name: PaxD SDK
author: mralfiem591
version: 1.2.4
description: The main SDK (Software Development Kit) for PaxD.
license: MIT
tags:
- sdk
- development
- devkit
install:
  files:
  - main.py
  firstrun: false
  updaterun: false
  exclude_from_updates: []
  supports_fastxd: false
  checksum:
    main.py: sha256:448f3fc008e0a10cc2a2e70dd4d0e694cfba970762659896004b965c1f1f826e
