name: PaxD SDK
author: mralfiem591
version: 1.2.3
description: The main SDK (Software Development Kit) for PaxD.
license: MIT
tags:
- sdk
- development
- devkit
install:
  files:
  - main.py
  firstrun: false
  updaterun: false
  checksums:
    main.py: sha256:17fbaf2d1fdf7fccd0c8a415cfa104e180005b7dc7afd7659e53e80ce90afa9c
  exclude_from_updates: []
  supports_fastxd: false
  checksum:
    main.py: sha256:17fbaf2d1fdf7fccd0c8a415cfa104e180005b7dc7afd7659e53e80ce90afa9c
