name: PaxD Publish
author: mralfiem591
version: 1.0.6
description: A tool to validate and publish PaxD packages to the repository via GitHub
  PR.
license: MIT
tags:
- cli
- publishing
- validation
- github
- tool
- automation
- package manager
install:
  files:
  - main.py
  - LICENSE
  dependencies:
    pip:
    - requests
    - PyGithub
    - pyyaml
    - gitpython
    paxd: []
  firstrun: false
  updaterun: false
  exclude_from_updates: []
  main_executable: main.py
  command_alias: paxdp
  supports_fastxd: true
  checksum:
    LICENSE: sha256:2ce014606d70c07902ca2505b7371ad29c7f854e3e45063fc750af340d2abde0
    main.py: sha256:203965454cfef0b8a6a864638178815cab21e9976eeb7d97629821f069dc468d
