name: PaxD GUI
author: mralfiem591
version: 1.1.10
description: A graphical user interface for PaxD package management.
license: MIT
tags:
- gui
- package manager
- installer
- windows
- paxd
- graphical
- tkinter
install:
  files:
  - paxd_gui.py
  dependencies:
    pip:
    - requests
    paxd:
    - com.mralfiem591.paxd-sdk
    - com.mralfiem591.paxd
  firstrun: true
  updaterun: false
  main_executable: paxd_gui.py
  command_alias: paxd-gui
  supports_fastxd: false
  checksum:
    paxd_gui.py: sha256:90f6d4e15236242af5e5955763314eb7282937370ee5722a0f3202051b62af50
