name: PaxD GUI
author: mralfiem591
version: 1.0.0
description: A graphical user interface for PaxD package management.
license: MIT
tags:
  - gui
  - package manager
  - installer
  - windows
  - paxd
  - graphical
  - tkinter

install:
  files:
    - paxd_gui.py
    - gui_components.py
    - package_manager.py
    - utils.py
    - launch.py

  dependencies:
    pip:
      - requests
    paxd:
      - com.mralfiem591.paxd-sdk
  
  firstrun: false
  updaterun: false
  main_executable: launch.py
  command_alias: paxd-gui
  supports_fastxd: true