name: PaxD GUI
author: mralfiem591
version: 1.0.10
description: A graphical user interface for PaxD package management.
license: MIT
tags:
  - gui
  - package manager
  - installer
  - windows
  - paxd
  - graphical
  - tkinter

install:
  files:
    - paxd_gui.py

  dependencies:
    pip:
      - requests
    paxd:
      - com.mralfiem591.paxd-sdk
  
  firstrun: false
  updaterun: false
  main_executable: paxd_gui.py
  command_alias: paxd-gui
  supports_fastxd: false # SDK cant be used in fastxd