# PaxD package configuration - converted from manifest
# Original file: paxd

name: PaxD Vulnerability Scanner
author: mralfiem591
version: 1.0.1
description: A simple vulnerability scanner for PaxD.
license: MIT
tags:
- cli
- vulnerability
- windows
- tool
install:
  files:
  - main.py
  dependencies:
    pip:
    - requests
    - colorama
    paxd:
    - com.mralfiem591.paxd-sdk
  firstrun: false
  updaterun: false
  main_executable: main.py
  command_alias: paxd-vulnscan,
  supports_fastxd: false

