# PaxD Hasher YAML package

name: PaxD Hasher
author: mralfiem591
version: 1.0.1
description: A tool for creating a "checksum" section of your PaxD package easily. Made to prepare for PaxD 26.0.12, where checksums are a requirement for all packages.
license: MIT
tags:
  - cli
  - utility
  - hasher
  - dev
  - paxd

install:
  files:
    - hasher.py

  checksums:
    hasher.py: sha256:071a5ec7f4af4ff91432b6ffe83fb7bdf8b86d32e58631163afe8a597422c8e4

  firstrun: false
  updaterun: false
  main_executable: hasher.py
  command_alias: paxd-hasher
  supports_fastxd: true
