# PaxD Hasher YAML package

name: PaxD Hasher
author: mralfiem591
version: 1.0.0
description: A tool for creating a "checksum" section of your PaxD package easily. Made to prepare for PaxD 26.0.12, where checksums are a requirement for all packages.
license: MIT
tags:
  - cli
  - utility
  - hasher
  - dev
  - paxd

install:
  files:
    - hasher.py

  firstrun: false
  updaterun: false
  main_executable: hasher.py
  command_alias: paxd-hasher
  supports_fastxd: true
